### ISSUE TITLE
Seems like a new dark substance rising

### ISSUE THREAD

**Issue by anqur** [thautwarm/JML.jl#1]
![rupy](https://i.imgflip.com/316qn2.jpg)

**Comment by thautwarm** [comment]
Tired now. This language uses `.pml` as file extension in fact, `Rupy` is an accident for I changed original goal in the process of implementation.

**Comment by anqur** [comment]
No further plans after this becoming public?  I mean this ML-like language can even be an excellent case study for MLStyle.jl, when it comes to fast-prototyping a new functional language.

**Comment by thautwarm** [comment]
It's made public mainly for supplying materials about my compiler skills(graduate application materials), and I use it instead of python regularly(it's compiled to Python but I didn't make that RTS project public. I will make it available when ice1000 help me out of the IDE problem).
